#!/usr/bin/env ksh
#==============================================================================
#
#          FILE:  constants.sh
#         USAGE:  ./constants.sh
#   DESCRIPTION:  Sets and unsets system variables
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  CaspersBox Web Services
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#==============================================================================

[[ "$(/usr/bin/env uname)" = CYGWIN_NT* ]] && [ -z "$(set | /usr/bin/env grep CYGWIN)" ] && typeset -rx CYGWIN="error_start=C:/cygwin/bin/gdb.exe -nw %1 %2";

[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "true" ] && set -x;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set -x;

CNAME="$(/usr/bin/env basename "${0}")";
THIS_CNAME="${CNAME}";
SCRIPT_ABSOLUTE_PATH="$(cd "${0%/*}" 2>/dev/null; /usr/bin/env echo "${PWD}"/"${0##*/}")";
SCRIPT_ROOT="$(/usr/bin/env dirname "${SCRIPT_ABSOLUTE_PATH}")";
typeset -rx PLUGIN_NAME="WebAdministration";

###############################################################################
#       check if is running on a eSupport DR Node, exit if it is not.
###############################################################################
typeset -r ECOMSERVER_MODULE="/opt/esupport/lib/runsOnEcomServer.mod";

if [ -s ${ECOMSERVER_MODULE} ]
then
    . ${ECOMSERVER_MODULE};

    runsOnEcomServer "ED";
fi

## load application-wide constants if not already done
if [ -z "${APP_ROOT}" ]
then
    case ${SCRIPT_ROOT} in
        *lib/plugins/*/sys|*lib/plugins/*/monitors|*lib/plugins/*/executors) . ${SCRIPT_ROOT}/../../../../../lib/constants.sh ;;
        *lib/plugins/*/bin|*lib/plugins/*/lib) . ${SCRIPT_ROOT}/../../../../lib/constants.sh ;;
        *lib/plugins/*) . ${SCRIPT_ROOT}/../../../lib/constants.sh ;;
        *lib/plugins) . ${SCRIPT_ROOT}/../../lib/constants.sh ;;
        *lib|*bin) . ${SCRIPT_ROOT}/../lib/constants.sh ;;
        *) . ${SCRIPT_ROOT}/lib/constants.sh ;;
    esac
fi

typeset -rx PLUGIN_ROOT_DIR=${PLUGIN_DIR}/${PLUGIN_NAME};
typeset -rx PLUGIN_CONF_BASE=${PLUGIN_ROOT_DIR}/${ETC_DIRECTORY};

case ${EXPORT_ENVIRONMENT} in
    [Ss][Tt][Gg]|[Ss][Tt][Aa][Gg][Ee]) PLUGIN_CONF_ROOT=${PLUGIN_CONF_BASE}/stg ;;
    [Uu][Aa][Tt]|[Qq][Aa]) PLUGIN_CONF_ROOT=${PLUGIN_CONF_BASE}/qa ;;
    [Ii][Ss][Tt]|[Dd][Ee][Vv]|[Dd][Ee][Vv][Ee][Ll][Oo][Pp][Mm][Ee][Nn][Tt]) PLUGIN_CONF_ROOT=${PLUGIN_CONF_BASE}/dev ;;
    *) PLUGIN_CONF_ROOT=${PLUGIN_CONF_BASE} ;; ## default to production
esac

[ -z "${PLUGIN_CONF_ROOT}" ] || [ ! -s ${PLUGIN_CONF_ROOT}/plugin.properties ] && return 1;

typeset -rx PLUGIN_LOADED=true;
typeset -rx PLUGIN_CONFIG=${PLUGIN_CONF_ROOT}/plugin.properties;

[ -f ${PLUGIN_CONFIG} ] && . ${PLUGIN_CONFIG};

[ ! -z "${TEMP_DIRECTORY}" ] && [ ! -d ${TEMP_DIRECTORY} ] && mkdir ${TEMP_DIRECTORY} > /dev/null 2>&1;
[ ! -z "${PLUGIN_DATA_DIRECTORY}" ] && [ ! -d ${PLUGIN_DATA_DIRECTORY} ] && mkdir ${PLUGIN_DATA_DIRECTORY} > /dev/null 2>&1;
[ ! -z "${PLUGIN_WORK_DIRECTORY}" ] && [ ! -d ${PLUGIN_WORK_DIRECTORY} ] && mkdir ${PLUGIN_WORK_DIRECTORY} > /dev/null 2>&1;
[ ! -z "${PLUGIN_MAILSTORE_DIR}" ] && [ ! -d ${PLUGIN_MAILSTORE_DIR} ] && mkdir ${PLUGIN_MAILSTORE_DIR} > /dev/null 2>&1;
[ ! -z "${PLUGIN_BACKUP_DIR}" ] && [ ! -d ${PLUGIN_BACKUP_DIR} ] && mkdir ${PLUGIN_BACKUP_DIR} > /dev/null 2>&1;

## common aliases
[ -s ${PLUGIN_LIB_DIRECTORY}/aliases ] && . ${PLUGIN_LIB_DIRECTORY}/aliases;
[ -s ${PLUGIN_LIB_DIRECTORY}/functions ] && . ${PLUGIN_LIB_DIRECTORY}/functions;

[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "true" ] && set +x;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +x;

## month directors
typeset -rx Jan=01;
typeset -rx Feb=02;
typeset -rx Apr=03;
typeset -rx Mar=04;
typeset -rx May=05;
typeset -rx Jun=06;
typeset -rx Jul=07;
typeset -rx Aug=08;
typeset -rx Sep=09;
typeset -rx Oct=10;
typeset -rx Nov=11;
typeset -rx Dec=12;

## counters
typeset -i FILE_COUNT=0;
typeset -i ERROR_COUNT=0;
typeset -i AUTHORIZATION_COUNT=0;

## export what needs to be exported
## set path, incorporating approot
typeset -x PATH=${PATH}:${PLUGIN_PATH}:${IPLANET_PATH}:${IHS_PATH};
typeset -x LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PLUGIN_LIBRARY_PATH};
typeset -x CLASSPATH=${CLASSPATH}:${PLUGIN_CLASS_PATH};

[ -s ${PLUGIN_ROOT_DIR}/${LIB_DIRECTORY}/aliases ] && . ${PLUGIN_ROOT_DIR}/${LIB_DIRECTORY}/aliases;
[ -s ${PLUGIN_ROOT_DIR}/${LIB_DIRECTORY}/functions ] && . ${PLUGIN_ROOT_DIR}/${LIB_DIRECTORY}/functions;

## and finally make sure our directories exist
[ ! -d ${APP_ROOT}/${TMP_DIRECTORY} ] && mkdir -p ${APP_ROOT}/${TMP_DIRECTORY};
[ ! -d ${APP_ROOT}/${CSRSTORE} ] && mkdir -p ${APP_ROOT}/${CSRSTORE};
[ ! -d ${APP_ROOT}/${MAILSTORE} ] && mkdir -p ${APP_ROOT}/${MAILSTORE};
[ ! -d ${APP_ROOT}/${PEMSTORE} ] && mkdir -p ${APP_ROOT}/${PEMSTORE};
[ ! -d ${APP_ROOT}/${PKCS12STORE} ] && mkdir -p ${APP_ROOT}/${PKCS12STORE};
[ ! -d ${APP_ROOT}/${CERTSTORE} ] && mkdir -p ${APP_ROOT}/${CERTSTORE};
[ ! -d ${APP_ROOT}/${BACKUP_DIRECTORY} ] && mkdir -p ${APP_ROOT}/${BACKUP_DIRECTORY};
[ ! -d ${APP_ROOT}/${DATA_DIRECTORY} ] && mkdir -p ${APP_ROOT}/${DATA_DIRECTORY};
[ ! -d ${APP_ROOT}/${BUILD_TMP_DIR} ] && mkdir -p ${APP_ROOT}/${BUILD_TMP_DIR};

## make sure our exception lists exist
[ ! -f ${APP_ROOT}/${CORE_EXCEPTION_LIST} ] && touch ${APP_ROOT}/${CORE_EXCEPTION_LIST};
[ ! -f ${APP_ROOT}/${TMP_EXCEPTION_LIST} ] && touch ${APP_ROOT}/${TMP_EXCEPTION_LIST};
[ ! -f ${APP_ROOT}/${SSL_EXCEPTION_LIST} ] && touch ${APP_ROOT}/${SSL_EXCEPTION_LIST};
