--
-- Definition of table `CWSSEC`.`SECURITY_QUESTIONS`
--
DROP TABLE IF EXISTS `CWSSEC`.`SECURITY_QUESTIONS`;
CREATE TABLE `CWSSEC`.`SECURITY_QUESTIONS` (
    `ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
    `QUESTION` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `IDX_QUESTIONS` (`ID`, `QUESTION`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

--
-- add in default questions
--
/*!40000 ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` DISABLE KEYS */;
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your mother''s maiden name ?');
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your favourite cartoon ?');
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your favourite car ?');
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your least favourite colour ?');
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('Who was your childhood best friend ?');
/*!40000 ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` ENABLE KEYS */;
COMMIT;

DELIMITER $$

--
-- Definition of procedure `CWSSEC`.`retrieveUserQuestions`
--
DROP PROCEDURE IF EXISTS `CWSSEC`.`retrieve_user_questions`$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `CWSSEC`.`retrieve_user_questions`(
)
BEGIN
    SELECT *
    FROM `CWSSEC`.`SECURITY_QUESTIONS`;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
