--
-- Definition of table ESOLUTIONSSVC.SERVICES
--
DROP TABLE IF EXISTS ESOLUTIONSSVC.SERVICES;
CREATE TABLE ESOLUTIONSSVC.SERVICES (
    GUID VARCHAR(128) NOT NULL UNIQUE,
    SERVICE_TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(128) NOT NULL UNIQUE,
    REGION VARCHAR(15) NOT NULL,
    NWPARTITION VARCHAR(15) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'INACTIVE',
    SERVERS TEXT,
    DESCRIPTION TEXT,
    PRIMARY KEY (GUID),
    FULLTEXT KEY IDX_PLATFORMS (SERVICE_TYPE, NAME, REGION, NWPARTITION)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE ESOLUTIONSSVC.SERVICES CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure ESOLUTIONSSVC.getServiceByAttribute
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.getServiceByAttribute$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.getServiceByAttribute(
    IN attributeName VARCHAR(100),
    IN startRow INT
)
BEGIN
    SELECT
        GUID,
        NAME,
    MATCH (SERVICE_TYPE, NAME, REGION, NWPARTITION)
    AGAINST (+attributeName WITH QUERY EXPANSION) AS score
    FROM ESOLUTIONSSVC.SERVICES
    WHERE MATCH (SERVICE_TYPE, NAME, REGION, NWPARTITION)
    AGAINST (+attributeName IN BOOLEAN MODE)
    AND STATUS = 'ACTIVE'
    LIMIT startRow, 20;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure ESOLUTIONSSVC.addNewService
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.addNewService$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.addNewService(
    IN guid VARCHAR(128),
    IN serviceType VARCHAR(50),
    IN name VARCHAR(128),
    IN region VARCHAR(15),
    IN nwpartition VARCHAR(15),
    IN status VARCHAR(50),
    IN servers TEXT,
    IN description TEXT
)
BEGIN
    INSERT INTO ESOLUTIONSSVC.SERVICES (GUID, SERVICE_TYPE, NAME, REGION, NWPARTITION, STATUS, SERVERS, DESCRIPTION)
    VALUES (guid, serviceType, name, region, nwpartition, status, servers, description);

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure ESOLUTIONSSVC.updateServiceData
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.updateServiceData$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.updateServiceData(
    IN guid VARCHAR(128),
    IN serviceType VARCHAR(50),
    IN name VARCHAR(128),
    IN region VARCHAR(15),
    IN nwpartition VARCHAR(15),
    IN status VARCHAR(50),
    IN servers TEXT,
    IN description TEXT
)
BEGIN
    UPDATE ESOLUTIONSSVC.SERVICES
    SET
        SERVICE_TYPE = serviceType,
        NAME = name,
        REGION = region,
        NWPARTITION = nwpartition,
        STATUS = status,
        SERVERS = servers,
        DESCRIPTION = description
    WHERE GUID = guid;

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure ESOLUTIONSSVC.removeServiceData
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.removeServiceData$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.removeServiceData(
    IN guid VARCHAR(128)
)
BEGIN
    UPDATE ESOLUTIONSSVC.SERVICES
    SET STATUS = 'INACTIVE'
    WHERE GUID = guid;

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure ESOLUTIONSSVC.listServices
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.listServices$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.listServices(
    IN startRow INT
)
BEGIN
    SET @counter := (SELECT COUNT(GUID) FROM ESOLUTIONSSVC.SERVICES WHERE STATUS = 'ACTIVE');

    SELECT
        @counter AS COUNTER,
        GUID,
        SERVICE_TYPE,
        NAME
    FROM ESOLUTIONSSVC.SERVICES
    WHERE STATUS = 'ACTIVE'
    LIMIT startRow, 20;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure ESOLUTIONSSVC.getServiceData
--
DROP PROCEDURE IF EXISTS ESOLUTIONSSVC.getServiceData$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE ESOLUTIONSSVC.getServiceData(
    IN guid VARCHAR(128)
)
BEGIN
    SELECT
        SERVICE_TYPE,
        NAME,
        REGION,
        NWPARTITION,
        STATUS,
        SERVERS,
        DESCRIPTION
    FROM ESOLUTIONSSVC.SERVICES
    WHERE GUID = guid
    AND STATUS = 'ACTIVE';
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;

