--
-- AUDIT / AUDIT_DATA
--
DELIMITER //

DROP TABLE IF EXISTS AUDIT.AUDIT_DATA //

CREATE TABLE AUDIT.AUDIT_DATA (
    SESSION_ID VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    USERNAME VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    CN VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    USER_ROLE VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    APPLICATION_ID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    APPLICATION_NAME VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    REQUEST_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    REQ_ACTION VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SOURCE_ADDRESS VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SOURCE_HOSTNAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    INDEX IDX_AUDIT (USERNAME, CN, USER_ROLE, APPLICATION_NAME, REQ_ACTION, SOURCE_ADDRESS, SOURCE_HOSTNAME ASC),
    FULLTEXT KEY FT_AUDIT (USERNAME, CN, USER_ROLE, APPLICATION_NAME, REQ_ACTION, SOURCE_ADDRESS, SOURCE_HOSTNAME)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON AUDIT.* TO 'appadm'@'localhost' //
GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON AUDIT.* TO 'appadm'@'appsrv.lan' //

--
--
--
DROP PROCEDURE IF EXISTS AUDIT.getAuditInterval //
DROP PROCEDURE IF EXISTS AUDIT.insertAuditEntry //

CREATE PROCEDURE AUDIT.getAuditInterval(
    IN userguid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN startRow INT
)
BEGIN
    SELECT
        SESSION_ID,
        USERNAME,
        CN,
        USER_ROLE,
        APPLICATION_ID,
        APPLICATION_NAME,
        REQUEST_TIMESTAMP,
        REQ_ACTION,
        SOURCE_ADDRESS,
        SOURCE_HOSTNAME
    FROM AUDIT.AUDIT_DATA
    WHERE CN = userguid
    ORDER BY REQUEST_TIMESTAMP DESC
    LIMIT startRow, 20;
END //
COMMIT //

CREATE PROCEDURE AUDIT.insertAuditEntry(
    IN usersessid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN username VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN userguid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN userrole VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN applid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN applname VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN useraction VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN srcaddr VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN srchost VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
)
BEGIN
    INSERT INTO AUDIT.AUDIT_DATA (SESSION_ID, USERNAME, CN, USER_ROLE, APPLICATION_ID, APPLICATION_NAME, REQUEST_TIMESTAMP, REQ_ACTION, SOURCE_ADDRESS, SOURCE_HOSTNAME)
    VALUES (usersessid, username, userguid, userrole, applid, applname, CURRENT_TIMESTAMP(), useraction, srcaddr, srchost);

    COMMIT;
END //
COMMIT //

GRANT EXECUTE ON PROCEDURE AUDIT.getAuditInterval TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE AUDIT.insertAuditEntry TO 'appadm'@'localhost' //

GRANT EXECUTE ON PROCEDURE AUDIT.getAuditInterval TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE AUDIT.insertAuditEntry TO 'appadm'@'appsrv.lan' //

DELIMITER ;
