DELIMITER //

DROP TABLE IF EXISTS ESOLUTIONS.ARTICLES //
DROP TABLE IF EXISTS ESOLUTIONS.APPLICATIONS //
DROP TABLE IF EXISTS ESOLUTIONS.SYSTEMS //
DROP TABLE IF EXISTS ESOLUTIONS.DATACENTERS //
DROP TABLE IF EXISTS ESOLUTIONS.SVCMESSAGING //
DROP TABLE IF EXISTS ESOLUTIONS.PLATFORMS //
DROP TABLE IF EXISTS ESOLUTIONS.DNSSERVICE //

CREATE TABLE ESOLUTIONS.ARTICLES (
    ID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    HITS TINYINT NOT NULL default 0,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    AUTHOR VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL default '',
    KEYWORDS VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL default '',
    TITLE VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL default '',
    SYMPTOMS VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL default '',
    CAUSE VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL default '',
    RESOLUTION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    STATUS VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'NEW',
    REVIEWED_BY VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    REVIEW_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_BY VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    PRIMARY KEY  (ID),
    FULLTEXT KEY articles (ID, KEYWORDS, TITLE, SYMPTOMS, CAUSE, RESOLUTION)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.DNSSERVICE (
    ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    ZONE_FILE VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, -- required for all entries, this will act as a correlator for apex/sub
    APEX_RECORD BOOLEAN NOT NULL DEFAULT FALSE,
    ORIGIN VARCHAR(126) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT ".", -- required for all entries
    TIMETOLIVE INTEGER, -- required for apex records and srv records (we're going to re-use it)
    HOSTNAME VARCHAR(126) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, -- required for apex records - 63 per label, including TLD this is 126
    OWNER VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for apex records
    HOSTMASTER VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for apex records
    SERIAL INTEGER, -- required for apex records
    REFRESH INTEGER, -- required for apex records
    RETRY INTEGER, -- required for apex records
    EXPIRES INTEGER, -- required for apex records
    CACHETIME INTEGER, -- required for apex records
    CLASS_NAME VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT "IN", -- required for all records
    CLASS_TYPE VARCHAR(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for all records
    PORT INTEGER, -- required for srv records
    WEIGHT INTEGER, -- required for srv and mx records
    SERVICE VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for srv records
    PROTOCOL VARCHAR(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for srv records
    PRIORITY INTEGER DEFAULT 10, -- required for srv records
    PRIMARY_TARGET VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- required for all records
    SECONDARY_TARGET VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- secondary target list, used for failover
    TERTIARY_TARGET VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- tertiary target list, used for failover
    PRIMARY KEY (ID),
    FULLTEXT KEY IDX_SEARCH (ZONE_FILE, ORIGIN, HOSTNAME, OWNER, CLASS_TYPE, SERVICE, PRIMARY_TARGET)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.APPLICATIONS (
    GUID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
    NAME VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    VERSION DECIMAL(30, 2) NOT NULL DEFAULT 1.0,
    INSTALLATION_PATH TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, -- where do files get installed to ?
    PACKAGE_LOCATION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- package location, either provided or scm'd or whatnot
    PACKAGE_INSTALLER TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- installer file for standalones
    INSTALLER_OPTIONS TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- only matters for standalone installs with an installer
    LOGS_DIRECTORY TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- applies only to web and standalone
    PLATFORM_GUID TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL, -- MULTIPLE platforms per app
    APP_ONLINE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), -- when did the app get added
    APP_OFFLINE_DATE TIMESTAMP,
    PRIMARY KEY (GUID),
    FULLTEXT KEY IDX_APPLICATIONS (NAME)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.DATACENTERS (
    GUID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    NAME VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    STATUS VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'INACTIVE',
    DESCRIPTION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    PRIMARY KEY (GUID),
    FULLTEXT KEY IDX_DATACENTERS (GUID, NAME, STATUS)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.SYSTEMS (
    GUID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SYSTEM_OSTYPE VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SYSSTATUS VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    REGION VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    NWPARTITION VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    DATACENTER_GUID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SYSTYPE VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    DOMAIN_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    CPU_TYPE VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    CPU_COUNT INT NOT NULL DEFAULT 1,
    SERVER_RACK VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    RACK_POSITION VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    SERVER_MODEL VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SERIAL_NUMBER VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    INSTALLED_MEMORY INT NOT NULL,
    OPER_IP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '127.0.0.1',
    OPER_HOSTNAME VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'localhost.localdomain',
    MGMT_IP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    MGMT_HOSTNAME VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    BKUP_IP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    BKUP_HOSTNAME VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    NAS_IP VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    NAS_HOSTNAME VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    NAT_ADDR VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    COMMENTS TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    ASSIGNED_ENGINEER VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    ADD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETE_DATE TIMESTAMP,
    DMGR_PORT INT DEFAULT 9043,
    OWNING_DMGR VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    MGR_ENTRY VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci, -- this could be a port number (for dmgr) or a url (for vmgr)
    PRIMARY KEY (GUID),
    CONSTRAINT FK_DATACENTER_GUID
        FOREIGN KEY (DATACENTER_GUID)
        REFERENCES ESOLUTIONS.DATACENTERS (GUID)
            ON DELETE RESTRICT
            ON UPDATE NO ACTION,
    FULLTEXT KEY IDX_SEARCH (GUID, SYSTEM_OSTYPE, SYSSTATUS, REGION, NWPARTITION, DATACENTER_GUID, SYSTYPE, OPER_HOSTNAME, ASSIGNED_ENGINEER, OWNING_DMGR)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.SVCMESSAGING (
    ID VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    TITLE VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    MESSAGE TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    AUTHOR VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    SUBMIT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    ALERT BOOLEAN NOT NULL DEFAULT FALSE,
    EXPIRES BOOLEAN NOT NULL DEFAULT FALSE,
    EXPIRES_ON TIMESTAMP,
    MODIFIED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    PRIMARY KEY (ID, TITLE), -- prevent the same message from being submitted twice (we hope)
    FULLTEXT KEY FTK_svcMessages (ID, TITLE, MESSAGE, AUTHOR)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

CREATE TABLE ESOLUTIONS.PLATFORMS (
    GUID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
    NAME VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
    REGION VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    NWPARTITION VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    STATUS VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'INACTIVE',
    SERVERS TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    DESCRIPTION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    PRIMARY KEY (GUID),
    FULLTEXT KEY IDX_PLATFORMS (NAME, REGION, NWPARTITION)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

DELIMITER ;
