--
-- Definition of table LOGON_DATA
-- DATA TABLE
--
DROP TABLE IF EXISTS CWSSEC.LOGON_DATA;
CREATE TABLE LOGON_DATA (
    CN VARCHAR(128) NOT NULL,
    SALT VARCHAR(128) NOT NULL,
    SALT_TYPE VARCHAR(15) DEFAULT NULL,
    PRIMARY KEY (SALT),
    UNIQUE KEY UNQ_SaltData (SALT) USING HASH,
    INDEX IDX_LOGON_DATA (CN, SALT, SALT_TYPE),
    CONSTRAINT FK_LGN_GUID
        FOREIGN KEY (CN)
        REFERENCES CWSSEC.USERS (CN)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    KEY IDX_SaltData (SALT,SALT_TYPE) USING HASH
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE CWSSEC.LOGON_DATA CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure CWSSEC.addUserSalt
--
DROP PROCEDURE IF EXISTS CWSSEC.addUserSalt$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE CWSSEC.addUserSalt(
    IN guid VARCHAR(100),
    IN salt VARCHAR(128),
    in sType VARCHAR(15)
)
BEGIN
    INSERT INTO CWSSEC.LOGON_DATA (CN, SALT, SALT_TYPE)
    VALUES (guid, salt, sType);

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure CWSSEC.retrUserSalt
--
DROP PROCEDURE IF EXISTS CWSSEC.retrUserSalt$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE CWSSEC.retrUserSalt(
    IN guid VARCHAR(100),
    IN sType VARCHAR(15)
)
BEGIN
    SELECT SALT
    FROM CWSSEC.LOGON_DATA
    WHERE CN = guid
    AND SALT_TYPE = sType;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure CWSSEC.updateUserSalt
--
DROP PROCEDURE IF EXISTS CWSSEC.updateUserSalt$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE CWSSEC.updateUserSalt(
    IN guid VARCHAR(100),
    IN saltValue VARCHAR(64),
    IN sType VARCHAR(15)
)
BEGIN
    UPDATE CWSSEC.LOGON_DATA
    SET SALT = saltValue
    WHERE CN = guid
    AND SALT_TYPE = sType;
    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure CWSSEC.removeUserData
--
DROP PROCEDURE IF EXISTS CWSSEC.removeUserData$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE CWSSEC.removeUserData(
    IN guid VARCHAR(100)
)
BEGIN
    DELETE FROM CWSSEC.LOGON_DATA
    WHERE CN = guid;
    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
