--
-- Definition of table ROLES
-- DATA TABLE
--
DROP TABLE IF EXISTS CWSSEC.ROLES;
CREATE TABLE CWSSEC.ROLES (
    ROLE
    MEMBERS
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE CWSSEC.ROLES CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure CWSSEC.passwordExpirationNotifier
--
DROP PROCEDURE IF EXISTS CWSSEC.passwordExpirationNotifier$$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE CWSSEC.passwordExpirationNotifier(
)
BEGIN
    SELECT
        UID,
        SN,
        GIVENNAME,
        CWSEXPIRYDATE,
        EMAIL
    FROM ROLES;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
