--
-- Definition of table `CWSSEC`.`KEY_DATA`
-- DATA TABLE
--
DROP TABLE IF EXISTS `CWSSEC`.`KEY_DATA`;
CREATE TABLE `CWSSEC`.`KEY_DATA` (
    `CN` VARCHAR(45) NOT NULL,
    `PRIVATE_KEY` VARBINARY(4352) NULL,
    PRIMARY KEY (`CN`),
    CONSTRAINT `FK_LGN_GUID`
        FOREIGN KEY (`CN`)
        REFERENCES `CWSSEC`.`USERS` (`CN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI;
COMMIT;

ALTER TABLE `CWSSEC`.`KEY_DATA` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
COMMIT;

DELIMITER $$

--
-- Definition of procedure `CWSSEC`.`addUserKeys`
--
DROP PROCEDURE IF EXISTS `CWSSEC`.`addUserKeys` $$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `CWSSEC`.`addUserKeys`(
    IN userGuid VARCHAR(45),
    IN privKey VARBINARY(4352)
)
BEGIN
    INSERT INTO KEY_DATA
    (CN, PRIVATE_KEY)
    VALUES
    (userGuid, privKey);

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `CWSSEC`.`retrUserKeys`
--
DROP PROCEDURE IF EXISTS `CWSSEC`.`retrUserKeys` $$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `CWSSEC`.`retrUserKeys`(
    IN userGuid VARCHAR(45)
)
BEGIN
    SELECT PRIVATE_KEY
    FROM KEY_DATA
    WHERE CN = userGuid;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

--
-- Definition of procedure `CWSSEC`.`retrUserKeys`
--
DROP PROCEDURE IF EXISTS `CWSSEC`.`deleteUserKeys` $$
/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER' */ $$
CREATE PROCEDURE `CWSSEC`.`deleteUserKeys`(
    IN userGuid VARCHAR(45)
)
BEGIN
    DELETE FROM `CWSSEC`.`KEY_DATA`
    WHERE CN = userGuid;

    UPDATE `CWSSEC`.`USERS`
    SET CWSPUBLICKEY = NULL
    WHERE CN = userGuid;

    COMMIT;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$
COMMIT$$

DELIMITER ;
COMMIT;
