DELIMITER //

DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`articles` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`installed_applications` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`installed_systems` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`service_datacenters` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`service_messages` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`service_platforms` //
DROP TABLE IF EXISTS `ESOLUTIONSSVC_HIST`.`dns_service` //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`articles` (
    `ID` VARCHAR(100) CHARACTER SET UTF8 NOT NULL default '',
    `HITS` TINYINT NOT NULL default 0,
    `CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `AUTHOR` VARCHAR(45) CHARACTER SET UTF8 NOT NULL default '',
    `KEYWORDS` VARCHAR(100) CHARACTER SET UTF8 NOT NULL default '',
    `TITLE` VARCHAR(100) CHARACTER SET UTF8 NOT NULL default '',
    `SYMPTOMS` VARCHAR(100) CHARACTER SET UTF8 NOT NULL default '',
    `CAUSE` VARCHAR(100) CHARACTER SET UTF8 NOT NULL default '',
    `RESOLUTION` TEXT NOT NULL,
    `STATUS` VARCHAR(15) CHARACTER SET UTF8 NOT NULL DEFAULT 'NEW',
    `REVIEWED_BY` VARCHAR(45) CHARACTER SET UTF8,
    `REVIEW_DATE` TIMESTAMP,
    `MODIFIED_DATE` TIMESTAMP,
    `MODIFIED_BY` VARCHAR(45) CHARACTER SET UTF8,
    PRIMARY KEY  (`ID`),
    FULLTEXT KEY `articles` (`ID`, `KEYWORDS`, `TITLE`, `SYMPTOMS`, `CAUSE`, `RESOLUTION`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`dns_service` (
    `ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ZONE_FILE` VARCHAR(128) CHARACTER SET UTF8 NOT NULL, -- required for all entries, this will act as a correlator for apex/sub
    `APEX_RECORD` BOOLEAN NOT NULL DEFAULT FALSE,
    `ORIGIN` VARCHAR(126) CHARACTER SET UTF8 NOT NULL DEFAULT ".", -- required for all entries
    `TIMETOLIVE` INTEGER, -- required for apex records and srv records (we're going to re-use it)
    `HOSTNAME` VARCHAR(126) CHARACTER SET UTF8 NOT NULL, -- required for apex records - 63 per label, including TLD this is 126
    `OWNER` VARCHAR(255) CHARACTER SET UTF8, -- required for apex records
    `HOSTMASTER` VARCHAR(255) CHARACTER SET UTF8, -- required for apex records
    `SERIAL` INTEGER(11), -- required for apex records
    `REFRESH` INTEGER, -- required for apex records
    `RETRY` INTEGER, -- required for apex records
    `EXPIRES` INTEGER, -- required for apex records
    `CACHETIME` INTEGER, -- required for apex records
    `CLASS_NAME` VARCHAR(8) CHARACTER SET UTF8 NOT NULL DEFAULT "IN", -- required for all records
    `CLASS_TYPE` VARCHAR(11) CHARACTER SET UTF8, -- required for all records
    `PORT` INTEGER(6), -- required for srv records
    `WEIGHT` INTEGER(3), -- required for srv and mx records
    `SERVICE` VARCHAR(10) CHARACTER SET UTF8, -- required for srv records
    `PROTOCOL` VARCHAR(6) CHARACTER SET UTF8, -- required for srv records
    `PRIORITY` INTEGER(3) DEFAULT 10, -- required for srv records
    `PRIMARY_TARGET` VARCHAR(255) CHARACTER SET UTF8, -- required for all records
    `SECONDARY_TARGET` VARCHAR(255) CHARACTER SET UTF8, -- secondary target list, used for failover
    `TERTIARY_TARGET` VARCHAR(255) CHARACTER SET UTF8, -- tertiary target list, used for failover
    PRIMARY KEY (`ID`),
    FULLTEXT KEY `IDX_SEARCH` (`ZONE_FILE`, `ORIGIN`, `HOSTNAME`, `OWNER`, `CLASS_TYPE`, `SERVICE`, `PRIMARY_TARGET`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`installed_applications` (
    `GUID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL UNIQUE,
    `NAME` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `VERSION` DECIMAL(30, 2) NOT NULL DEFAULT 1.0,
    `INSTALLATION_PATH` TEXT CHARACTER SET UTF8 NOT NULL, -- where do files get installed to ?
    `PACKAGE_LOCATION` TEXT CHARACTER SET UTF8, -- package location, either provided or scm'd or whatnot
    `PACKAGE_INSTALLER` TEXT CHARACTER SET UTF8, -- installer file for standalones
    `INSTALLER_OPTIONS` TEXT CHARACTER SET UTF8, -- only matters for standalone installs with an installer
    `LOGS_DIRECTORY` TEXT CHARACTER SET UTF8, -- applies only to web and standalone
    `PLATFORM_GUID` TEXT CHARACTER SET UTF8 NOT NULL, -- MULTIPLE platforms per app
    `APP_ONLINE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), -- when did the app get added
    `APP_OFFLINE_DATE` TIMESTAMP,
    PRIMARY KEY (`GUID`),
    FULLTEXT KEY `IDX_APPLICATIONS` (`NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`installed_systems` (
    `GUID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `SYSTEM_OSTYPE` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `STATUS` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `REGION` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `NWPARTITION` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `DATACENTER_GUID` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `SYSTYPE` VARCHAR(45) CHARACTER SET UTF8 NOT NULL,
    `DOMAIN_NAME` VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    `CPU_TYPE` VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    `CPU_COUNT` INT NOT NULL DEFAULT 1,
    `SERVER_RACK` VARCHAR(255) CHARACTER SET UTF8,
    `RACK_POSITION` VARCHAR(255) CHARACTER SET UTF8,
    `SERVER_MODEL` VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    `SERIAL_NUMBER` VARCHAR(255) CHARACTER SET UTF8 NOT NULL,
    `INSTALLED_MEMORY` INT NOT NULL,
    `OPER_IP` VARCHAR(50) CHARACTER SET UTF8 NOT NULL DEFAULT '127.0.0.1',
    `OPER_HOSTNAME` VARCHAR(100) CHARACTER SET UTF8 NOT NULL DEFAULT 'localhost.localdomain',
    `MGMT_IP` VARCHAR(50) CHARACTER SET UTF8,
    `MGMT_HOSTNAME` VARCHAR(100) CHARACTER SET UTF8,
    `BKUP_IP` VARCHAR(50) CHARACTER SET UTF8,
    `BKUP_HOSTNAME` VARCHAR(100) CHARACTER SET UTF8,
    `NAS_IP` VARCHAR(50) CHARACTER SET UTF8,
    `NAS_HOSTNAME` VARCHAR(100) CHARACTER SET UTF8,
    `NAT_ADDR` VARCHAR(50) CHARACTER SET UTF8,
    `COMMENTS` TEXT CHARACTER SET UTF8,
    `ASSIGNED_ENGINEER` VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    `ADD_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DELETE_DATE` TIMESTAMP,
    `DMGR_PORT` INT(5) DEFAULT 0,
    `OWNING_DMGR` VARCHAR(255) CHARACTER SET UTF8,
    `MGR_ENTRY` VARCHAR(128) CHARACTER SET UTF8, -- this could be a port number (for dmgr) or a url (for vmgr)
    PRIMARY KEY (`GUID`),
    CONSTRAINT `FK_DATACENTER_GUID`
        FOREIGN KEY (`DATACENTER_GUID`)
        REFERENCES `ESOLUTIONSSVC_HIST`.`service_datacenters` (`DATACENTER_GUID`)
            ON DELETE RESTRICT
            ON UPDATE NO ACTION,
    FULLTEXT KEY `IDX_SEARCH` (`GUID`, `SYSTEM_OSTYPE`, `STATUS`, `REGION`, `NWPARTITION`, `DATACENTER_GUID`, `SYSTYPE`, `OPER_HOSTNAME`, `ASSIGNED_ENGINEER`, `OWNING_DMGR`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`service_datacenters` (
    `GUID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `NAME` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `STATUS` VARCHAR(50) CHARACTER SET UTF8 NOT NULL DEFAULT 'INACTIVE',
    `DESCRIPTION` TEXT CHARACTER SET UTF8,
    PRIMARY KEY (`GUID`),
    FULLTEXT KEY `IDX_DATACENTERS` (`GUID`, `NAME`, `STATUS`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`service_messages` (
    `ID` VARCHAR(16) CHARACTER SET UTF8 NOT NULL,
    `TITLE` VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    `MESSAGE` TEXT CHARACTER SET UTF8 NOT NULL,
    `AUTHOR` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `SUBMIT_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `ALERT` BOOLEAN NOT NULL DEFAULT FALSE,
    `EXPIRES` BOOLEAN NOT NULL DEFAULT FALSE,
    `EXPIRES_ON` TIMESTAMP,
    `MODIFIED_ON` TIMESTAMP,
    `MODIFIED_BY` VARCHAR(128) CHARACTER SET UTF8,
    PRIMARY KEY (`ID`, `TITLE`), -- prevent the same message from being submitted twice (we hope)
    FULLTEXT KEY `FTK_svcMessages` (`ID`, `TITLE`, `MESSAGE`, `AUTHOR`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `ESOLUTIONSSVC_HIST`.`service_platforms` (
    `GUID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL UNIQUE,
    `NAME` VARCHAR(128) CHARACTER SET UTF8 NOT NULL UNIQUE,
    `REGION` VARCHAR(15) CHARACTER SET UTF8 NOT NULL,
    `NWPARTITION` VARCHAR(15) CHARACTER SET UTF8 NOT NULL,
    `STATUS` VARCHAR(50) CHARACTER SET UTF8 NOT NULL DEFAULT 'INACTIVE',
    `SERVERS` TEXT CHARACTER SET UTF8 NOT NULL,
    `DESCRIPTION` TEXT,
    PRIMARY KEY (`GUID`),
    FULLTEXT KEY `IDX_PLATFORMS` (`NAME`, `REGION`, `NWPARTITION`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

ALTER TABLE `ESOLUTIONSSVC_HIST`.`articles` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`dns_service` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`installed_applications` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`installed_systems` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`service_datacenters` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`service_messages` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `ESOLUTIONSSVC_HIST`.`service_platforms` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //

COMMIT //

DELIMITER ;
