#!/bin/sh

SERVER_ROOT=&SERVER_ROOT&
INSTANCE_ROOT=&SERVER_ROOT&
INSTANCE_NAME=&SERVER_ID&

. ${SERVER_ROOT}/bin/https/bin/wsenv

MPS_LIB_DIRS=/usr/lib/mps/secv1:/usr/lib/mps:/usr/lib/mps/sasl2

#Set the LD_LIBRARY PATH to Sun shared lib locations for Linux.
LINUX_SHAREDLIB_DIRS=/opt/sun/private/lib:/opt/sun/private/share/lib:/opt/sun/lib

LD_LIBRARY_PATH=${WS_INSTALLROOT}/bin/https/lib:${LD_LIBRARY_PATH}:${LINUX_SHAREDLIB_DIRS}:${MPS_LIB_DIRS}; export LD_LIBRARY_PATH
LIBPATH=${LIBPATH}:${LD_LIBRARY_PATH}:/usr/lib/threads:/usr/ibmcxx/lib:/usr/lib:/lib; export LIBPATH
SHLIB_PATH=${SHLIB_PATH}:${LD_LIBRARY_PATH}; export SHLIB_PATH

cd ${SERVER_ROOT}/bin/https/httpadmin/bin

if [ $# -eq 0 ]
then
	arg="-reconfig";
fi

case $arg in
        -reconfig)
		./commit ${INSTANCE_NAME}
		if test $? -ne 0 ; then
			exit 1
		fi
		;;
	*)
		echo "Usage: reconfig"
		exit 1
		;;
esac

exit 0
