#!/usr/bin/env ksh
#==============================================================================
#
#          FILE:  constants.sh
#         USAGE:  ./constants.sh
#   DESCRIPTION:  Sets and unsets system variables
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kevin Huntly <kmhuntly@gmail.com>
#       COMPANY:  CaspersBox Web Services
#       VERSION:  1.0
#       CREATED:  ---
#      REVISION:  ---
#
#==============================================================================

[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "true" ] && set -x;
[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set -x;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "true" ] && set -v;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set -v;

[ ! -z "${APPLICATION_LOADED}" ] && [ "${APPLICATION_LOADED}" = "${_TRUE}" ] && return 0;

trap 'set +vx' INT TERM EXIT;

[[ "$(/usr/bin/env uname)" == CYGWIN_NT* ]] && [ -z "$(set | /usr/bin/env grep CYGWIN)" ] && typeset -rx CYGWIN="winsymlinks:lnk error_start=C:\cygwin\bin\gdb.exe -nw %1 %2";

case "${SCRIPT_ROOT}" in
    *lib/plugins/*/sys|*lib/plugins/*/monitors|*lib/plugins/*/executors) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/../../../../../etc/application.properties" ;;
    *lib/plugins/*/bin|*lib/plugins/*/lib) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/../../../../etc/application.properties" ;;
    *lib/plugins/*) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/../../../etc/application.properties" ;;
    *lib/plugins) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/../../etc/application.properties" ;;
    *lib|*bin) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/../etc/application.properties" ;;
    *) typeset -rx APP_SYS_CONFIG="${SCRIPT_ROOT}/etc/application.properties" ;;
esac

if [ ! -s ${APP_SYS_CONFIG} ]
then
    /usr/bin/env echo "Failed to locate configuration data. Cannot continue.";

    /usr/bin/env echo 1; exit 1;
fi

case $(uname) in
    [Cc][Yy][Gg][Ww][Ii][Nn]*)
        typeset -rx PATHSEP=";";
        ;;
    *)
        typeset -rx PATHSEP=":";
        ;;
esac

. ${APP_SYS_CONFIG};

## path
typeset -x PATH=${PATH}:${APP_PATH}:${SYS_PATH};
typeset -x LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APP_LIB_PATH};

## system constants
case $(uname) in
    SunOS)
        typeset -rx SYSTEM_ARCHITECTURE=$(/usr/bin/env isainfo -b);
        ;;
    AIX)
        typeset -rx SYSTEM_ARCHITECTURE=$(/usr/bin/env getconf HARDWARE_BITMODE);
        ;;
    *)
        typeset -rx SYSTEM_ARCHITECTURE=$(/usr/bin/env uname -m);
        ;;
esac

typeset -rx SYSTEM_PLATFORM=$(/usr/bin/env uname -s);
typeset -rx SYSTEM_HOSTNAME="$(/usr/bin/env uname -n)";
typeset -rx SYSTEM_UPTIME="$(/usr/bin/env uptime | /usr/bin/env cut -d "," -f 1 | /usr/bin/env sed -e 's/^ *//g;s/ *$//g')";

## uncommon constants
typeset -rx DATESYS=$(/usr/bin/env date +%Y%m%d_%H-%M-%S);
typeset -rx CURRENT_DATE=$(/usr/bin/env date '+%Y%m%d');
typeset -rx CURRENT_TIMESTAMP=$(/usr/bin/env date '+%Y%m%d%H%M');
typeset -rx IS_EXPECT_INSTALLED=$(/usr/bin/env expect -v 2>/dev/null);
set -A IUSER_GROUPS $(groups); typeset -rx IUSER_GROUPS;
[ -z "$(/usr/bin/env who am i | /usr/bin/env awk '{print $1}')" ] && typeset -rx IUSER_AUDIT=$(/usr/bin/env whoami) || typeset -rx IUSER_AUDIT=$(/usr/bin/env who am i | /usr/bin/env awk '{print $1}');

## counters
typeset -x -i A=0;
typeset -x -i B=0;
typeset -x -i C=0;
typeset -x -i D=0;
typeset -x -i ERROR_COUNT=0;
typeset -x -i RETRY_COUNT=0;
typeset -x -i STATUS=0;

## source aliases/functions ..
[ -f "${APP_ROOT}/${LIB_DIRECTORY}/aliases" ] && . "${APP_ROOT}/${LIB_DIRECTORY}/aliases";
[ -f "${APP_ROOT}/${LIB_DIRECTORY}/functions" ] && . "${APP_ROOT}/${LIB_DIRECTORY}/functions";

## create directories
[ ! -d ${TMP_DIRECTORY} ] && mkdir ${TMP_DIRECTORY} > /dev/null 2>&1;

## build classpath...
for JARFILE in ${LOAD_CLASSES_FROM}/*.jar
do
    [ ! -f "${JARFILE}" ] && continue;

    typeset -x CLASSPATH="${CLASSPATH}${PATHSEP}${JARFILE}";
done

typeset -rx APPLICATION_LOADED="${_TRUE}";

[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "true" ] && set +x;
[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "true" ] && set +v;
[ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
