--
-- CWSSEC / KEY_DATA
--
DELIMITER //

DROP TABLE IF EXISTS CWSSEC.KEY_DATA //

CREATE TABLE CWSSEC.KEY_DATA (
    CN VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    PRIVATE_KEY VARBINARY(4352) NULL,
    PRIMARY KEY (CN),
    CONSTRAINT FK_KEY_DATA
        FOREIGN KEY (CN)
        REFERENCES CWSSEC.USERS (CN)
            ON DELETE CASCADE
            ON UPDATE CASCADE
) ENGINE=InnoDB CHARSET=UTF8MB4 ROW_FORMAT=COMPACT COLLATE utf8mb4_0900_ai_ci //
COMMIT //

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'localhost' //
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'appsrv.lan' //

--
-- BEGIN STORED PROCEDURES FOR TABLE KEY_DATA
--
DROP PROCEDURE IF EXISTS CWSSEC.addUserKeys //
DROP PROCEDURE IF EXISTS CWSSEC.retrUserKeys //
DROP PROCEDURE IF EXISTS CWSSEC.deleteUserKeys //

CREATE PROCEDURE CWSSEC.addUserKeys(
    IN userGuid VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    IN privKey VARBINARY(4352)
)
BEGIN
    INSERT INTO CWSSEC.KEY_DATA (CN, PRIVATE_KEY)
    VALUES (userGuid, privKey);

    COMMIT;
END //
COMMIT //

CREATE PROCEDURE CWSSEC.retrUserKeys(
    IN userGuid VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
)
BEGIN
    SELECT PRIVATE_KEY
    FROM CWSSEC.KEY_DATA
    WHERE CN = userGuid;
END //
COMMIT //

CREATE PROCEDURE CWSSEC.deleteUserKeys(
    IN userGuid VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci
)
BEGIN
    DELETE FROM CWSSEC.KEY_DATA
    WHERE CN = userGuid;

    UPDATE CWSSEC.USERS
    SET CWSPUBLICKEY = NULL
    WHERE CN = userGuid;

    COMMIT;
END //
COMMIT //

GRANT EXECUTE ON PROCEDURE CWSSEC.addUserKeys TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE CWSSEC.retrUserKeys TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE CWSSEC.deleteUserKeys TO 'appadm'@'localhost' //

GRANT EXECUTE ON PROCEDURE CWSSEC.addUserKeys TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE CWSSEC.retrUserKeys TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE CWSSEC.deleteUserKeys TO 'appadm'@'appsrv.lan' //

DELIMITER ;
