--
-- CWSSEC / LOGON_DATA
--
DELIMITER //

DROP TABLE IF EXISTS CWSSEC.LOGON_DATA //

CREATE TABLE CWSSEC.LOGON_DATA (
    CN VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    SALT VARCHAR(128) NOT NULL,
    SALT_TYPE VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    PRIMARY KEY (SALT),
    UNIQUE KEY UNQ_SALTDATA (SALT) USING HASH,
    INDEX IDX_LOGON_DATA (CN, SALT, SALT_TYPE),
    CONSTRAINT FK_LGN_DATA
        FOREIGN KEY (CN)
        REFERENCES CWSSEC.USERS (CN)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    KEY IDX_SALTDATA (SALT,SALT_TYPE) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 ROW_FORMAT=COMPACT COLLATE utf8mb4_general_ci //
COMMIT //

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'localhost' //
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'appsrv.lan' //

--
-- BEGIN STORED PROCEDURES
--
DROP PROCEDURE IF EXISTS CWSSEC.addUserSalt //
DROP PROCEDURE IF EXISTS CWSSEC.getUserSalt //
DROP PROCEDURE IF EXISTS CWSSEC.updateUserSalt //

CREATE PROCEDURE CWSSEC.addUserSalt(
    IN guid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    IN salt VARCHAR(128),
    in sType VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
)
BEGIN
    INSERT INTO CWSSEC.LOGON_DATA (CN, SALT, SALT_TYPE)
    VALUES (guid, salt, sType);

    COMMIT;
END //
COMMIT //

CREATE PROCEDURE CWSSEC.getUserSalt(
    IN guid VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    IN sType VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
)
BEGIN
    SELECT SALT
    FROM CWSSEC.LOGON_DATA
    WHERE CN = guid
    AND SALT_TYPE = sType;
END //
COMMIT //

CREATE PROCEDURE CWSSEC.updateUserSalt(
    IN guid VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    IN saltValue VARCHAR(128),
    IN sType VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
)
BEGIN
    UPDATE CWSSEC.LOGON_DATA
    SET SALT = saltValue
    WHERE CN = guid
    AND SALT_TYPE = sType;

    COMMIT;
END //
COMMIT //

GRANT EXECUTE ON PROCEDURE CWSSEC.addUserSalt TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE CWSSEC.getUserSalt TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE CWSSEC.updateUserSalt TO 'appadm'@'localhost' //

GRANT EXECUTE ON PROCEDURE CWSSEC.addUserSalt TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE CWSSEC.getUserSalt TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE CWSSEC.updateUserSalt TO 'appadm'@'appsrv.lan' //

DELIMITER ;
