DELIMITER //

DROP TABLE IF EXISTS `CWSSEC`.`USERS` //
DROP TABLE IF EXISTS `CWSSEC`.`LOGON_DATA` //
DROP TABLE IF EXISTS `CWSSEC`.`RESET_DATA` //
DROP TABLE IF EXISTS `CWSSEC`.`SECURITY_QUESTIONS` //
DROP TABLE IF EXISTS `CWSSEC`.`AUDIT` //
DROP TABLE IF EXISTS `CWSSEC`.`KEY_DATA` //
DROP TABLE IF EXISTS `CWSSEC`.`USER_SERVICES` //
DROP TABLE IF EXISTS `CWSSEC`.`SERVICE_MAP` //
DROP TABLE IF EXISTS `CWSSEC`.`CONTACT_DATA` //

CREATE TABLE `CWSSEC`.`USERS` (
    `CN` VARCHAR(128) NOT NULL,
    `UID` VARCHAR(45) NOT NULL,
    `USERPASSWORD` VARCHAR(255) NOT NULL,
    `CWSROLE` VARCHAR(45) NOT NULL DEFAULT '3517632B-E77F-49FF-BD99-A42EA8335DCC',
    `CWSFAILEDPWDCOUNT` MEDIUMINT NOT NULL DEFAULT '0',
    `CWSLASTLOGIN` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    `CWSISSUSPENDED` BOOLEAN NOT NULL DEFAULT FALSE,
    `CWSISOLRSETUP` BOOLEAN NOT NULL DEFAULT TRUE,
    `CWSISOLRLOCKED` BOOLEAN NOT NULL DEFAULT FALSE,
    `CWSISTCACCEPTED` BOOLEAN NOT NULL DEFAULT FALSE,
    `SN` VARCHAR(100) NOT NULL DEFAULT 'Surname',
    `GIVENNAME` VARCHAR(100) NOT NULL DEFAULT 'Given Name',
    `DISPLAYNAME` VARCHAR(100) NOT NULL DEFAULT 'Display Name',
    `CWSEXPIRYDATE` BIGINT(20) UNSIGNED NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `CWSSECQ1` VARCHAR(60) NOT NULL DEFAULT 'Question 1',
    `CWSSECQ2` VARCHAR(60) NOT NULL DEFAULT 'Question 2',
    `CWSSECANS1` VARCHAR(255) NOT NULL DEFAULT 'Answer 1',
    `CWSSECANS2` VARCHAR(255) NOT NULL DEFAULT 'Answer 2',
    `CWSPUBLICKEY` VARBINARY(4352),
    PRIMARY KEY (`CN`),
    UNIQUE KEY `USERID` (`UID`),
    INDEX `IDX_USERS` (`CN`, `UID`),
    FULLTEXT KEY `FT_USERS` (`UID`, `CWSROLE`, `GIVENNAME`, `SN`, `CN`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `CWSSEC`.`CONTACT_DATA` (
    `CN` VARCHAR(128) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL DEFAULT 'user@domain.com',
    `TELEPHONENUMBER` INTEGER(10),
    `PAGER` INTEGER(10),
    PRIMARY KEY (`CN`),
    UNIQUE KEY `EMAIL` (`EMAIL`),
    INDEX `IDX_CONTACT` (`CN`, `EMAIL`),
    FULLTEXT KEY `FT_USERS` (`EMAIL`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `CWSSEC`.`LOGON_DATA` (
    `CN` VARCHAR(128) NOT NULL,
    `SALT` VARCHAR(128) NOT NULL,
    `SALT_TYPE` VARCHAR(15) DEFAULT NULL,
    PRIMARY KEY (`SALT`),
    UNIQUE KEY `UNQ_SaltData` (`SALT`) USING HASH,
    INDEX `IDX_LOGON_DATA` (`CN`, `SALT`, `SALT_TYPE`),
    CONSTRAINT `FK_LGN_GUID`
        FOREIGN KEY (`CN`)
        REFERENCES `CWSSEC`.`USERS` (`CN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    KEY `IDX_SaltData` (`SALT`,`SALT_TYPE`) USING HASH
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `CWSSEC`.`RESET_DATA` (
    `CN` VARCHAR(128) NOT NULL,
    `RESET_KEY` VARCHAR(128) NOT NULL,
    `SMS_CODE` VARCHAR(8),
    `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`CN`),
    CONSTRAINT `FK_LGN_GUID`
        FOREIGN KEY (`CN`)
        REFERENCES `CWSSEC`.`USERS` (`CN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    INDEX `IDX_USERS` (`CN`, `RESET_KEY`, `SMS_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `CWSSEC`.`SECURITY_QUESTIONS` (
    `ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
    `QUESTION` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `IDX_QUESTIONS` (`ID`, `QUESTION`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

/*!40000 ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` DISABLE KEYS */ //
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your mother''s maiden name ?') //
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your favourite cartoon ?') //
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your favourite car ?') //
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('What is your least favourite colour ?') //
INSERT INTO `CWSSEC`.`SECURITY_QUESTIONS` (QUESTION) VALUES ('Who was your childhood best friend ?') //
/*!40000 ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` ENABLE KEYS */ //
COMMIT //

CREATE TABLE `CWSSEC`.`KEY_DATA` (
    `CN` VARCHAR(45) NOT NULL,
    `PRIVATE_KEY` VARBINARY(4352) NULL,
    PRIMARY KEY (`CN`),
    CONSTRAINT `FK_LGN_GUID`
        FOREIGN KEY (`CN`)
        REFERENCES `CWSSEC`.`USERS` (`CN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

CREATE TABLE `CWSSEC`.`USER_SERVICES` (
    `ID` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `NAME` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `URI` VARCHAR(128) CHARACTER SET UTF8 NOT NULL,
    `DESCRIPTION` TEXT CHARACTER SET UTF8 NOT NULL,
    PRIMARY KEY (`ID`),
    INDEX `IDX_SERVICES` (`ID`, `NAME` DESC)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

/*!40000 ALTER TABLE `CWSSEC`.`USER_SERVICES` DISABLE KEYS */ //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('3517632B-E77F-49FF-BD99-A42EA8335DCC', 'NONE', 'NONE', 'Service ID for no rights') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('96E4E53E-FE87-446C-AF03-0F5BC6527B9D', 'AppMgmt', 'application-management', 'Service ID for Application Management') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('B52B1DE9-37A4-4554-B85E-2EA28C4EE3DD', 'DNSMgmt', 'dns-service', 'Service ID for DNS Management') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('F7D1DAB8-DADB-4E7B-8596-89D1BE230E75', 'FileMgmt', 'application-management', 'Service ID for File Handling') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('4B081972-92C3-455B-9403-B81E68C538B6', 'kbase', 'knowledgebase', 'Service ID for KnowledgeBase') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('5C0B0A54-2456-45C9-A435-B485ED36FAC7', 'Messaging', 'service-messaging', 'Service ID for Messaging') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('7CE2B9E8-9FCF-4096-9CAE-10961F50FA81', 'Search', 'search', 'Service ID for Search') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('45F6BC9E-F45C-4E2E-B5BF-04F93C8F512E', 'SysMgmt', 'system-management', 'Service ID for System Management') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('D1B5D088-32B3-4AA1-9FCF-822CB476B649', 'PlatformMgmt', 'service-management', 'Service ID for Platform Management') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('3F0D3FB5-56C9-4A90-B177-4E1593088DBF', 'SystemCheck', 'system-check', 'Service ID for System Checks') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('AEB46994-57B4-4E92-90AA-A4046F60B830', 'UserMgmt', 'user-management', 'Service ID for User Management') //
INSERT INTO `CWSSEC`.`USER_SERVICES` VALUES ('0C1C5F83-3EDD-4635-9F1E-6A9B5383747E', 'DatacenterMgmt', 'service-management', 'Service ID for Datacenter Management') //
/*!40000 ALTER TABLE `CWSSEC`.`USER_SERVICES` ENABLE KEYS */ //
COMMIT //

CREATE TABLE `CWSSEC`.`SERVICE_MAP` (
    `CN` VARCHAR(128) NOT NULL,
    `ID` VARCHAR(128) NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_CN`
        FOREIGN KEY (`CN`)
        REFERENCES `CWSSEC`.`USERS` (`CN`)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    CONSTRAINT `FK_SVC_ID`
        FOREIGN KEY (`ID`)
        REFERENCES `CWSSEC`.`USER_SERVICES` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    INDEX `IDX_USERS` (`CN`, `ID`),
    FULLTEXT KEY `FT_SERVICEMAP` (`CN`, `ID`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COLLATE UTF8_GENERAL_CI //
COMMIT //

ALTER TABLE `CWSSEC`.`USERS` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`LOGON_DATA` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`RESET_DATA` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`SECURITY_QUESTIONS` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`AUDIT` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`KEY_DATA` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`USER_SERVICES` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
ALTER TABLE `CWSSEC`.`SERVICE_MAP` CONVERT TO CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI //
COMMIT //

DELIMITER ;
