--
-- CWSSEC / ACCESS_GROUPS
--
DELIMITER //

DROP TABLE IF EXISTS CWSSEC.ACCESS_GROUPS //

CREATE TABLE ESOLUTIONS.USER_SERVICES (
    GROUP_ID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL UNIQUE,
    GROUP_NAME VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
    GROUP_DESC VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
    PRIMARY KEY (GROUP_ID),
    UNIQUE KEY SVCNAME (GROUP_NAME),
    INDEX IDX_SERVICES(GROUP_ID, GROUP_NAME)
) ENGINE=InnoDB CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COLLATE utf8mb4_0900_ai_ci //
COMMIT //

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON ESOLUTIONS.* TO 'appadm'@'localhost' //
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON ESOLUTIONS.* TO 'appadm'@'appsrv.lan' //

/*!40000 ALTER TABLE ESOLUTIONS.USER_SERVICES DISABLE KEYS */ //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('2864dd4a-611c-4181-bc20-8494776d2d1e', 'NONE', 'NONE', 'Service ID for no rights') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('df9d70cf-1141-4d41-baef-acd5febd84df', 'Application Management', 'application-management', 'Service ID for Application Management') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('af8838f8-a969-4e2a-9f2f-4f09033f25a9', 'DNS Management', 'Service ID for DNS Management') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('5da1cb4d-d17e-4397-9331-0d1e5c9aea2c', 'Knowledge Base', 'Service ID for KnowledgeBase') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('d12b3360-27da-4d1c-b4b1-724c1b89f960', 'Messaging', 'Service ID for Messaging') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('5c0d85f5-596d-4ff1-a28b-7cf4d81ba48b', 'Server Management', 'Service ID for Server Management') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('527c044a-1153-4aa6-9955-18e588feabf7', 'Platform Management', 'Service ID for Platform Management') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('07aea3f0-36d4-4dd3-9b55-dba588e98f44', 'System Checks', 'Service ID for System Checks') //
INSERT INTO ESOLUTIONS.USER_SERVICES VALUES ('27f9e32e-dfba-4007-99cb-e586dd89b0c5', 'Datacenter Management', 'Service ID for Datacenter Management') //
/*!40000 ALTER TABLE ESOLUTIONS.USER_SERVICES ENABLE KEYS */ //

COMMIT //

--
--
--
DROP PROCEDURE IF EXISTS ESOLUTIONS.retrAvailableServices //
DROP PROCEDURE IF EXISTS ESOLUTIONS.isServiceEnabled //

CREATE PROCEDURE ESOLUTIONS.getAvailableGroups(
)
BEGIN
    SELECT GROUP_ID, GROUP_NAME, GROUP_DESC
    FROM CWSSEC.ACCESS_GROUPS
    ORDER BY GROUP_NAME ASC;
END //
COMMIT //

GRANT EXECUTE ON PROCEDURE ESOLUTIONS.retrAvailableServices TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE ESOLUTIONS.isServiceEnabled TO 'appadm'@'localhost' //

GRANT EXECUTE ON PROCEDURE ESOLUTIONS.retrAvailableServices TO 'appadm'@'appsrv.lan' //
GRANT EXECUTE ON PROCEDURE ESOLUTIONS.isServiceEnabled TO 'appadm'@'appsrv.lan' //

DELIMITER ;
