--
-- CWSSEC / USER_SERVICES
--
DELIMITER //

DROP TABLE IF EXISTS CWSSEC.USER_SERVICES //

CREATE TABLE CWSSEC.USER_SERVICES (
    ID VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    SVCNAME VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    URI VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    DESCRIPTION TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID),
    UNIQUE KEY SVCNAME (SVCNAME),
    INDEX IDX_SERVICES(ID, SVCNAME, URI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COLLATE utf8mb4_general_ci //
COMMIT //

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'localhost' //
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'appsrv.lan' //

/*!40000 ALTER TABLE CWSSEC.USER_SERVICES DISABLE KEYS */ //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('3517632B-E77F-49FF-BD99-A42EA8335DCC', 'NONE', 'NONE', 'Service ID for no rights', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('96E4E53E-FE87-446C-AF03-0F5BC6527B9D', 'AppMgmt', 'application-management', 'Service ID for Application Management', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('B52B1DE9-37A4-4554-B85E-2EA28C4EE3DD', 'DNSMgmt', 'dns-service', 'Service ID for DNS Management', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('F7D1DAB8-DADB-4E7B-8596-89D1BE230E75', 'FileMgmt', 'application-management', 'Service ID for File Handling', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('4B081972-92C3-455B-9403-B81E68C538B6', 'kbase', 'knowledgebase', 'Service ID for KnowledgeBase', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('5C0B0A54-2456-45C9-A435-B485ED36FAC7', 'Messaging', 'service-messaging', 'Service ID for Messaging', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('7CE2B9E8-9FCF-4096-9CAE-10961F50FA81', 'Search', 'search', 'Service ID for Search', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('45F6BC9E-F45C-4E2E-B5BF-04F93C8F512E', 'SysMgmt', 'system-management', 'Service ID for System Management', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('D1B5D088-32B3-4AA1-9FCF-822CB476B649', 'PlatformMgmt', 'service-management', 'Service ID for Platform Management', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('3F0D3FB5-56C9-4A90-B177-4E1593088DBF', 'SystemCheck', 'system-check', 'Service ID for System Checks', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('AEB46994-57B4-4E92-90AA-A4046F60B830', 'UserMgmt', 'user-management', 'Service ID for User Management', TRUE) //
INSERT INTO CWSSEC.USER_SERVICES VALUES ('0C1C5F83-3EDD-4635-9F1E-6A9B5383747E', 'DatacenterMgmt', 'service-management', 'Service ID for Datacenter Management', TRUE) //
/*!40000 ALTER TABLE CWSSEC.USER_SERVICES ENABLE KEYS */ //

COMMIT //

--
--
--
DROP PROCEDURE IF EXISTS CWSSEC.retrAvailableServices //

CREATE PROCEDURE CWSSEC.retrAvailableServices(
)
BEGIN
    SELECT URI, ID
    FROM CWSSEC.USER_SERVICES
    ORDER BY ID ASC;
END //
COMMIT //

GRANT EXECUTE ON PROCEDURE CWSSEC.retrAvailableServices TO 'appadm'@'localhost' //
GRANT EXECUTE ON PROCEDURE CWSSEC.retrAvailableServices TO 'appadm'@'appsrv.lan' //

DELIMITER ;
