--
-- AUDIT / AUDIT_DATA
--
DELIMITER //

DROP DATABASE IF EXISTS AUDIT //
DROP DATABASE IF EXISTS CWSSEC //

CREATE DATABASE AUDIT DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci //
CREATE DATABASE CWSSEC DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci //

GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON AUDIT.* TO 'appadm'@'localhost' //
GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON AUDIT.* TO 'appadm'@'appsrv.lan' //

GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'localhost' //
GRANT SELECT, UPDATE, INSERT, DELETE, EXECUTE ON CWSSEC.* TO 'appadm'@'appsrv.lan' //

DELIMITER ;
